# Generated by Django 4.2.10 on 2025-04-07 22:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('versao', models.CharField(max_length=10, verbose_name='Versão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_modificacao', models.DateTimeField(auto_now=True, verbose_name='Última Modificação')),
            ],
            options={
                'verbose_name': 'Modelo de Documento',
                'verbose_name_plural': 'Modelos de Documentos',
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NOTEBOOK', 'Notebook'), ('DESKTOP', 'Desktop'), ('MONITOR', 'Monitor'), ('CELULAR', 'Celular'), ('TABLET', 'Tablet'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('numero_serie', models.CharField(max_length=100, unique=True, verbose_name='Número de Série')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data_aquisicao', models.DateField(verbose_name='Data de Aquisição')),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('EM_USO', 'Em Uso'), ('MANUTENCAO', 'Em Manutenção'), ('INATIVO', 'Inativo')], default='DISPONIVEL', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
            },
        ),
        migrations.CreateModel(
            name='ItemTermo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrega', models.DateField(verbose_name='Data de Entrega')),
                ('estado_entrega', models.TextField(verbose_name='Estado na Entrega')),
                ('data_devolucao', models.DateField(blank=True, null=True, verbose_name='Data de Devolução')),
                ('estado_devolucao', models.TextField(blank=True, verbose_name='Estado na Devolução')),
            ],
            options={
                'verbose_name': 'Item do Termo',
                'verbose_name_plural': 'Itens do Termo',
            },
        ),
        migrations.CreateModel(
            name='TermoResponsabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADO', 'Enviado'), ('ASSINADO', 'Assinado'), ('RECUSADO', 'Recusado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('data_envio', models.DateTimeField(blank=True, null=True, verbose_name='Data de Envio')),
                ('data_assinatura', models.DateTimeField(blank=True, null=True, verbose_name='Data da Assinatura')),
                ('ip_assinatura', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP da Assinatura')),
                ('hash_assinatura', models.CharField(blank=True, max_length=64, verbose_name='Hash da Assinatura')),
                ('documento_pdf', models.FileField(blank=True, null=True, upload_to='documentos/termos/%Y/%m/', verbose_name='Documento PDF')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Termo de Responsabilidade',
                'verbose_name_plural': 'Termos de Responsabilidade',
            },
        ),
    ]
