# Generated by Django 4.2.10 on 2025-04-07 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='termoresponsabilidade',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='termos_responsabilidade', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='termoresponsabilidade',
            name='equipamentos',
            field=models.ManyToManyField(related_name='termos', through='documents.ItemTermo', to='documents.equipamento'),
        ),
        migrations.AddField(
            model_name='termoresponsabilidade',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='termos', to='documents.documentomodelo'),
        ),
        migrations.AddField(
            model_name='itemtermo',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.equipamento'),
        ),
        migrations.AddField(
            model_name='itemtermo',
            name='termo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.termoresponsabilidade'),
        ),
    ]
