# Generated by Django 4.2.10 on 2025-04-09 20:09

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_equipamento_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentomodelo',
            name='conteudo',
            field=tinymce.models.HTMLField(verbose_name='Conteúdo'),
        ),
    ]
