# Generated by Django 4.2.10 on 2025-04-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_documentomodelo_conteudo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termoresponsabilidade',
            name='documento_pdf',
        ),
        migrations.AddField(
            model_name='termoresponsabilidade',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='documentos/termos/', verbose_name='Arquivo PDF'),
        ),
    ]
