# Generated by Django 4.2.10 on 2025-04-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_remove_termoresponsabilidade_documento_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentomodelo',
            name='arquivo_word',
            field=models.FileField(blank=True, help_text='Upload de um arquivo Word (.docx) como modelo', null=True, upload_to='documentos/modelos/', verbose_name='Arquivo Word'),
        ),
    ]
