# Generated by Django 4.2.10 on 2025-04-15 10:46

from django.db import migrations
from django.conf import settings
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_auto_20250415_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='usuario',
            field=models.ForeignKey(
                blank=True, 
                null=True, 
                on_delete=models.CASCADE, 
                related_name='equipamentos', 
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
