# Generated by Django 4.2.10 on 2025-04-15 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_usuario_equipamento_nullable'),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Recriando a tabela sem a restrição NOT NULL
            CREATE TABLE "new_documents_equipamento" (
                "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                "tipo" varchar(20) NOT NULL,
                "marca" varchar(100) NOT NULL,
                "modelo" varchar(100) NOT NULL,
                "numero_serie" varchar(100) NOT NULL UNIQUE,
                "descricao" text NOT NULL,
                "valor" decimal NOT NULL,
                "data_aquisicao" date NOT NULL,
                "status" varchar(20) NOT NULL,
                "observacoes" text NOT NULL,
                "usuario_id" integer NULL REFERENCES "users_user" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
            );
            
            -- Copiando os dados
            INSERT INTO "new_documents_equipamento" 
            SELECT "id", "tipo", "marca", "modelo", "numero_serie", "descricao", "valor", "data_aquisicao", "status", "observacoes", "usuario_id"
            FROM "documents_equipamento";
            
            -- Removendo a tabela antiga
            DROP TABLE "documents_equipamento";
            
            -- Renomeando a nova tabela
            ALTER TABLE "new_documents_equipamento" RENAME TO "documents_equipamento";
            
            -- Recriando outros índices necessários
            CREATE INDEX "documents_equipamento_usuario_id_idx" ON "documents_equipamento" ("usuario_id");
            """,
            reverse_sql="""
            -- Se precisar reverter, recriaremos a tabela original (não ideal pois perderia dados)
            """,
        )
    ]
